In [3]:
import numpy as np
import pandas as pd

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['feature1', 'feature2', 'feature3'])
df1['target'] = 0

# Use pd.concat() instead of append
df = pd.concat([df, df1], ignore_index=True)

# Shuffle the combined DataFrame
df = df.sample(40).reset_index(drop=True)


In [4]:
df.head()

feature1  feature2  feature3  target
0 -0.367548 -1.137460 -1.322148       1
1  0.177061 -0.598109  1.226512       0
2  0.420623  0.411620 -0.071324       1
3  1.968435 -0.547788 -0.679418       1
4 -2.506230  0.146960  0.606195       1

In [5]:
import plotly.express as px
#y_train_trf = y_train.astype(str)
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [6]:
df.iloc[:,0:3]

feature1  feature2  feature3
0  -0.367548 -1.137460 -1.322148
1   0.177061 -0.598109  1.226512
2   0.420623  0.411620 -0.071324
3   1.968435 -0.547788 -0.679418
4  -2.506230  0.146960  0.606195
5   1.425140  1.441152  0.182561
6   2.224431  0.230401  1.192120
7   0.322272  0.060343 -1.043450
8  -0.723253  1.461259 -0.085367
9   2.823378 -0.332863  2.637391
10 -1.389866  0.666726  1.343517
11 -0.331617 -1.632386  0.619114
12  0.666988  0.025813 -0.777619
13 -1.009942  0.441736  1.128877
14  0.384865  1.323546 -0.103193
15  1.676860  4.187503 -0.080565
16  0.241106 -0.952510 -0.136267
17 -0.045438  1.040886 -0.094035
18 -0.992574 -0.161346  1.192404
19  1.437892  1.099723  1.065406
20  0.290746  0.866975  0.982643
21  0.731858  0.517441  2.244610
22 -1.027861  1.131416  2.603234
23 -0.420844 -0.551989 -0.121098
24 -0.764314  1.566504  1.548788
25  2.011059  1.920996  2.933090
26  0.898907  0.435960  0.820964
27  1.010229  1.437830  2.327788
28  0.948634  0.701672 -1.051082
29  1.415320  0.457711  0.728876
30  1.250737  0.186384  1.703624
31  0.204637 -0.011535  3.150780
32  0.748855  2.593111  1.170818
33  1.045371  0.538162  0.812119
34 -1.838068 -0.938769 -0.201841
35  0.190141  0.512137  0.131538
36 -0.022539  0.013422  0.935945
37  1.267248  0.173634 -1.223255
38  1.233898  0.052778 -0.261576
39  1.772258 -0.347459  0.670140

In [7]:
# Step 1 - Apply standard scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [8]:
# Step 2 - Find Covariance Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covariance Matrix:\n', covariance_matrix)

Covariance Matrix:
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]


In [16]:
# Step 3 - Finding EV and EVs
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [17]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [18]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [19]:
pc = eigen_vectors[0:2]
pc
     

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [20]:
transformed_df = np.dot(df.iloc[:,0:3],pc.T)
# (40,3) . (3,2) === (40,2)
new_df = pd.DataFrame(transformed_df,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df

PC1       PC2  target
0   0.354836  1.250883       1
1   0.905912 -1.035385       0
2  -0.546230 -0.226495       1
3  -1.005401 -0.772965       1
4   1.538160  1.185298       1
5  -1.680149 -1.088015       0
6  -0.788253 -2.361439       0
7  -0.714391  0.575327       1
8  -0.664735  0.523479       0
9  -0.029210 -3.839064       0
10  0.928721 -0.109021       0
11  1.606958 -0.232360       1
12 -0.749057  0.148930       1
13  0.777467 -0.193933       1
14 -1.174745 -0.188630       0
15 -3.846534 -1.083651       0
16  0.465640 -0.045283       1
17 -0.742474  0.089762       1
18  1.216802 -0.246888       1
19 -1.028075 -1.758979       0
20 -0.288170 -0.941439       0
21  0.320015 -2.179448       0
22  1.013676 -1.302042       0
23  0.551710  0.373328       1
24  0.065730 -0.683852       0
25 -1.013533 -3.553090       0
26 -0.394160 -1.213880       0
27 -0.428602 -2.434583       0
28 -1.500345  0.163358       1
29 -0.731500 -1.483429       1
30  0.011432 -2.108137       0
31  1.404246 -2.511761       0
32 -1.642312 -1.402252       0
33 -0.548189 -1.304379       1
34  1.544930  1.368166       1
35 -0.394783 -0.229426       1
36  0.450340 -0.691632       1
37 -1.388059  0.089829       1
38 -0.826451 -0.612709       0
39 -0.393395 -1.664772       1

In [21]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()