In [14]:
import subprocess
import sys

# Function to install packages using pip
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])

# Install pandas and numpy
install('pandas')
install('numpy')


In [16]:
import numpy as np

In [17]:
x=[[1,2,3],[4,5,6],[7,8,9]]
x

np.array(x) ##Prints the list as a Matrix !

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.random.seed(101)
np.random.randint (1,10,5)



array([2, 7, 8, 9, 5])

In [19]:
np.random.seed(101) #same random number
arr =np.random.randint (1,10,6) #random list
arr.reshape(2,3) # Converts in Matrix

array([[2, 7, 8],
       [9, 5, 9]])

In [ ]:
arr=np.arange(1, 11)
arr_max=arr.max()
arr_max


10

In [ ]:
arr_min=arr.min()
arr_min

1

In [ ]:
arr.argmax() ##Which position holds max value

9

In [ ]:
random_array = np.random.choice(range(1, 11), size=5, replace=False)
print(random_array)
""" The array range(1, 11) contains integers from 1 to 10.
size=5 specifies that you want to select 5 random elements from this array.
replace=False ensures that the selected elements are unique. """

[ 1  5 10  2  3]


' The array range(1, 11) contains integers from 1 to 10.\nsize=5 specifies that you want to select 5 random elements from this array.\nreplace=False ensures that the selected elements are unique. '

In [9]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[ :3] ##first 3 element print

array([1, 2, 3])

In [12]:
arr[3:] ##print except frist 3 elements

array([ 4,  5,  6,  7,  8,  9, 10])

In [14]:
arr[3:6]

array([4, 5, 6])

In [17]:
arr [1:10:2] ##steps

array([ 2,  4,  6,  8, 10])

In [18]:
arr[1::2]

array([ 2,  4,  6,  8, 10])

In [19]:
arr[:6:2]

array([1, 3, 5])

In [20]:
arr[::2]

array([1, 3, 5, 7, 9])

In [23]:
arr[10:1:-2] #Stop slicing at index 1 (the 2nd element), exclusive.

array([10,  8,  6,  4])

In [30]:
arr[8:1:-2]

array([9, 7, 5, 3])

##**Broadcast**

*   Replaces Values in an array
*   Prblm : Replaces the main array



In [39]:
arr_main=np.arange(1,11)
arr_main

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[1:5]=20
arr

array([ 1, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [36]:
arr[0:10:2]=10
arr

array([10, 20, 10, 20, 10,  6, 10,  8, 10, 10])

In [45]:
modified_arr= arr_main.copy() ##so that main array doesnt get affected
modified_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
modified_arr[1:10:2]=10
print(arr_main)
print(modified_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1 10  3 10  5 10  7 10  9 10]


## **Conditionals**

In [48]:
arr_main

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr_main >5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
conditional_arr= arr_main.copy()

In [61]:
conditional_arr[arr_main %2 == 0]

array([ 2,  4,  6,  8, 10])

## **Operations**

In [62]:
arr_main

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
np.sqrt(arr_main) ##arr_main's every element's square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [64]:
np.exp(arr_main)  ##exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [65]:
np.log(arr_main) ##logarithm

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [66]:
np.sum(arr_main)

55

In [68]:
arr_main.sum()

55

In [70]:
arr_main.max()

10

In [71]:
np.max(arr_main)

10

In [73]:
arr_main.std() ##Standard_div

2.8722813232690143

In [74]:
np.std(arr_main)

2.8722813232690143

## **Axis Logic**

2D Array basic :
arr_2d[start_row:stop_row:step_row, start_col:stop_col:step_col]

In [77]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
arr_2d.sum(axis=0) ##Collumn wise Addition

array([15, 18, 21, 24])

In [80]:
arr_2d.sum(axis=1) ##Row wise addition

array([10, 26, 42])

In [82]:
np.sum(arr_2d,axis=1)

array([10, 26, 42])

In [83]:
np.sum(arr_2d,axis=0)

array([15, 18, 21, 24])

In [85]:
arr_2d.shape

(3, 4)

In [84]:
np.shape(arr_2d)

(3, 4)

In [86]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
arr_2d[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
arr_2d[:1]

array([[1, 2, 3, 4]])

In [90]:
arr_2d[1]  # Second row (index 1)

array([5, 6, 7, 8])

In [91]:
arr_2d[1:2]  # Second row only


array([[5, 6, 7, 8]])

In [93]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
arr_2d[0, 1:]  # First row, from the second column to the end (Row,Col : ....)


array([2, 3, 4])

In [96]:
arr_2d[0,0:3] #first row,first col , 3rd item

array([1, 2, 3])

In [97]:
arr_2d[:, 1:]  # All rows, from the second column to the end


array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [99]:
arr_2d[1:, 1:]  # From the second row and second column to the end


array([[ 6,  7,  8],
       [10, 11, 12]])

In [100]:
arr_2d[:, 1]  # All rows, second column only


array([ 2,  6, 10])

In [101]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
arr_2d[1:,1:3]

array([[ 6,  7],
       [10, 11]])